import { Archivo_Black, Geist, Geist_Mono, Outfit } from "next/font/google";
import { ReactNode } from "react";
import "@/src/app/globals.css";
import Navbar from "../_ui/Navbar";
import MainContainer from "../_ui/MainContainer";
import Header from "../_ui/Header";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: Readonly<ReactNode>;
}) {
  return (
    <html
      lang="en"
      className={`${outfit.className} ${outfit.variable} dark h-full antialiased`}
    >
      <body className="bg-black-950 relative flex h-dvh grow flex-col items-center justify-center gap-5 px-2 py-2 md:flex-row md:px-5 md:py-10">
        <MainContainer>
          <Header />
          {children}
        </MainContainer>
        <Navbar />
      </body>
    </html>
  );
}
